baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[taxonomies]
category = "categories"
country = "countries"
tag = "tags"
sector = "sectors"
tactic = "tactics"
technique = "techniques"
